### Local routes

GET http://localhost:3000/contacts 

###

GET http://localhost:3000/contacts/650f87f45c20df689a0b8fd6 HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Jack2",
    "lastName": "Sparrow2",
    "email": "theSparrow2@test.com",
    "favoriteColor": "brown",
    "birthday": "06/19/1985"
}

###

PUT http://localhost:3000/contacts/650f87f45c20df689a0b8fd6 HTTP/1.1
content-type: application/json

{
    "firstName": "James",
    "lastName": "Potter",
    "email": "mariliaw@test.com",
    "favoriteColor": "red",
    "birthday": "03/27/1960"
}

###

DELETE http://localhost:3000/contacts/650f87f45c20df689a0b8fd6 HTTP/1.1
content-type: application/json

########################################################################################

### Published routes

GET https://project2-cgay.onrender.com/contacts 

###

GET https://project2-cgay.onrender.com/contacts/650f87f45c20df689a0b8fd6 HTTP/1.1
content-type: application/json

###

POST https://project2-cgay.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Jack",
    "lastName": "Sparrow",
    "email": "theSparrow@test.com",
    "favoriteColor": "brown",
    "birthday": "06/19/1985"
}

###

PUT https://project2-cgay.onrender.com/contacts/650f87f45c20df689a0b8fd6 HTTP/1.1
content-type: application/json

{
    "firstName": "James",
    "lastName": "Potter",
    "email": "mariliaw@test.com",
    "favoriteColor": "red",
    "birthday": "03/27/1960"
}

###

DELETE https://project2-cgay.onrender.com/contacts/650f87f45c20df689a0b8fd6 HTTP/1.1
content-type: application/json